import eslint from "@eslint/js";
import angular from "angular-eslint";
import prettier from "eslint-plugin-prettier/recommended";
import unicorn from "eslint-plugin-unicorn";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig(
  eslint.configs.recommended,
  unicorn.configs.all,
  prettier,
  {
    files: ["**/*.html"],
    extends: [...angular.configs.templateAll, ...angular.configs.templateAccessibility],
    rules: {
      "@angular-eslint/template/i18n": "off",
      "@angular-eslint/template/cyclomatic-complexity": "warn",
      "@angular-eslint/template/no-call-expression": "off",
    },
  },
  {
    files: ["**/*.ts"],
    extends: [...tseslint.configs.strictTypeChecked, ...angular.configs.tsAll],
    processor: angular.processInlineTemplates,
    languageOptions: {
      parserOptions: {
        project: ["tsconfig.json", "tsconfig.spec.json"],
        // @ts-expect-error - esm
        tsconfigDirName: import.meta.dirname,
      },
    },
    rules: {
      "@angular-eslint/prefer-on-push-component-change-detection": "off",
      "@angular-eslint/prefer-signals": "warn",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/consistent-type-imports": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-empty-interface": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-extraneous-class": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-use-before-define": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          "argsIgnorePattern": "^_",
          "caughtErrorsIgnorePattern": "^_",
          "destructuredArrayIgnorePattern": "^_",
          "varsIgnorePattern": "^_",
        },
      ],
      "@typescript-eslint/array-type": ["error", { "default": "array-simple" }],
      "@typescript-eslint/prefer-for-of": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
    },
  },
  {
    // As ferramentas do parser são .mjs tipados por JSDoc; só o tsconfig.spec.json do
    // pacote liga `allowJs`, sem o qual os testes não resolvem o que importam delas.
    files: ["packages/parser/**/*.ts"],
    languageOptions: {
      parserOptions: {
        project: ["packages/parser/tsconfig.spec.json"],
        // @ts-expect-error - esm
        tsconfigDirName: import.meta.dirname,
      },
    },
  },
  {
    ignores: [
      "node_modules/",
      ".angular/",
      "packages/**/coverage/",
      "packages/**/lib/",
      "packages/**/dist/",
      "packages/**/node_modules/",
      // Arquivos gerados:
      "packages/antlr/src/Portugol*.ts",
      "packages/parser/src/bibliotecas/*.gerado.ts",
      "packages/resources/assets/",
      "packages/resources/recursos.temp/",
      "packages/ide/src/index.html",
    ],
  },
  {
    rules: {
      "camelcase": "off",
      "capitalized-comments": "off",
      "func-names": ["error", "always"],
      "lines-between-class-members": "off",
      "new-cap": "off",
      "no-alert": "off",
      "no-await-in-loop": "off",
      "no-bitwise": "off",
      "no-case-declarations": "off",
      "no-empty": "off",
      "no-template-curly-in-string": "off",
      "no-undef": "off",
      "no-unused-vars": "off",
      "no-useless-constructor": "off",
      "no-useless-escape": "off",
      "no-warning-comments": "off",
      "prefer-destructuring": "off",
      "prefer-named-capture-group": "off",
      "require-unicode-regexp": "off",
      "unicorn/comment-content": "off",
      "unicorn/consistent-boolean-name": "off",
      "unicorn/consistent-class-member-order": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/custom-error-definition": "off",
      "unicorn/filename-case": "off",
      "unicorn/max-nested-calls": ["error", { "max": 5 }],
      "unicorn/name-replacements": "off",
      "unicorn/no-abusive-eslint-disable": "off",
      "unicorn/no-array-front-mutation": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/no-asterisk-prefix-in-documentation-comments": "off",
      "unicorn/no-await-expression-member": "off",
      "unicorn/no-barrel-files": "off",
      "unicorn/no-error-property-assignment": "off",
      "unicorn/no-for-loop": "off",
      "unicorn/no-incorrect-template-string-interpolation": "off",
      "unicorn/no-keyword-prefix": "off",
      "unicorn/no-lonely-if": "off",
      "unicorn/no-null": "off",
      "unicorn/no-object-as-default-parameter": "off",
      "unicorn/no-top-level-assignment-in-function": "off",
      "unicorn/no-unreadable-new-expression": "off",
      "unicorn/no-unsafe-string-replacement": "off",
      "unicorn/no-useless-override": "off",
      "unicorn/no-useless-recursion": "off",
      "unicorn/no-useless-template-literals": "off",
      "unicorn/prefer-await": "off",
      "unicorn/prefer-continue": "off",
      "unicorn/prefer-early-return": "off",
      "unicorn/prefer-error-is-error": "off",
      "unicorn/prefer-export-from": "off",
      "unicorn/prefer-global-this": "off",
      "unicorn/prefer-number-coercion": "off",
      "unicorn/prefer-spread": "off",
      "unicorn/prefer-string-raw": "off",
      "unicorn/prefer-temporal": "off",
      "unicorn/prefer-ternary": "off",
      "unicorn/prefer-top-level-await": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/require-post-message-target-origin": "off",
      "unicorn/try-complexity": "off",
    },
  },
);
