import * as monaco from "monaco-editor";

/**
 * The basic completions for the Portugol language.
 */
export const PortugolBasicCompletions: Array<Partial<monaco.languages.CompletionItem>> = [
  {
    label: "escreva",
    kind: monaco.languages.CompletionItemKind.Function,
    insertText: "escreva",
    documentation: "Escreve um texto no console",
    detail: "(função) escreva(...argumentos: qualquer)",
  },
  {
    label: "leia",
    kind: monaco.languages.CompletionItemKind.Function,
    insertText: "leia",
    documentation: "Lê um texto do console",
    detail: "(função) leia(variavel: qualquer): cadeia",
  },
  {
    label: "inteiro",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "inteiro",
    documentation: "Tipo de dado inteiro",
    detail: "inteiro",
  },
  {
    label: "real",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "real",
    documentation: "Tipo de dado real",
    detail: "real",
  },
  {
    label: "vazio",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "vazio",
    documentation: "Tipo de dado vazio",
    detail: "vazio",
  },
  {
    label: "logico",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "logico",
    documentation: "Tipo de dado lógico",
    detail: "logico",
  },
  {
    label: "cadeia",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "cadeia",
    documentation: "Tipo de dado cadeia",
    detail: "cadeia",
  },
  {
    label: "caracter",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "caracter",
    documentation: "Tipo de dado caracter",
    detail: "caracter",
  },
  {
    label: "faca",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "faca",
    documentation: "Inicia um laço de repetição",
    detail: "faca",
  },
  {
    label: "enquanto",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "enquanto",
    documentation: "Inicia um laço de repetição",
    detail: "enquanto",
  },
  {
    label: "para",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "para",
    documentation: "Inicia um laço de repetição",
    detail: "para",
  },
  {
    label: "se",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "se",
    documentation: "Inicia uma estrutura condicional",
    detail: "se",
  },
  {
    label: "senao",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "senao",
    documentation: "Inicia uma estrutura condicional",
    detail: "senao",
  },
  {
    label: "const",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "const",
    documentation: "Declara uma constante",
    detail: "const",
  },
  {
    label: "funcao",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "funcao",
    documentation: "Declara uma função",
    detail: "funcao",
  },
  {
    label: "programa",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "programa",
    documentation: "Declara um programa",
    detail: "programa",
  },
  {
    label: "escolha",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "escolha",
    documentation: "Inicia uma estrutura condicional",
    detail: "escolha",
  },
  {
    label: "caso",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "caso",
    documentation: "Inicia uma estrutura condicional",
    detail: "caso",
  },
  {
    label: "contrario",
    kind: monaco.languages.CompletionItemKind.Keyword,
    insertText: "contrario",
    documentation: "Inicia uma estrutura condicional",
    detail: "contrario",
  },
];
