export default /* javascript */ `{
    TECLA_0: new PortugolVar("inteiro", 48, true),
    TECLA_0_NUM: new PortugolVar("inteiro", 96, true),
    TECLA_1: new PortugolVar("inteiro", 49, true),
    TECLA_1_NUM: new PortugolVar("inteiro", 97, true),
    TECLA_2: new PortugolVar("inteiro", 50, true),
    TECLA_2_NUM: new PortugolVar("inteiro", 98, true),
    TECLA_3: new PortugolVar("inteiro", 51, true),
    TECLA_3_NUM: new PortugolVar("inteiro", 99, true),
    TECLA_4: new PortugolVar("inteiro", 52, true),
    TECLA_4_NUM: new PortugolVar("inteiro", 100, true),
    TECLA_5: new PortugolVar("inteiro", 53, true),
    TECLA_5_NUM: new PortugolVar("inteiro", 101, true),
    TECLA_6: new PortugolVar("inteiro", 54, true),
    TECLA_6_NUM: new PortugolVar("inteiro", 102, true),
    TECLA_7: new PortugolVar("inteiro", 55, true),
    TECLA_7_NUM: new PortugolVar("inteiro", 103, true),
    TECLA_8: new PortugolVar("inteiro", 56, true),
    TECLA_8_NUM: new PortugolVar("inteiro", 104, true),
    TECLA_9: new PortugolVar("inteiro", 57, true),
    TECLA_9_NUM: new PortugolVar("inteiro", 105, true),
    TECLA_A: new PortugolVar("inteiro", 65, true),
    TECLA_ABRE_COLCHETES: new PortugolVar("inteiro", 91, true),
    TECLA_ADICAO: new PortugolVar("inteiro", 107, true),
    TECLA_AJUDA: new PortugolVar("inteiro", 156, true),
    TECLA_ALT: new PortugolVar("inteiro", 18, true),
    TECLA_B: new PortugolVar("inteiro", 66, true),
    TECLA_BACKSPACE: new PortugolVar("inteiro", 8, true),
    TECLA_BARRA: new PortugolVar("inteiro", 47, true),
    TECLA_BARRA_INVERTIDA: new PortugolVar("inteiro", 92, true),
    TECLA_C: new PortugolVar("inteiro", 67, true),
    TECLA_CANCELAR: new PortugolVar("inteiro", 3, true),
    TECLA_CAPS_LOCK: new PortugolVar("inteiro", 20, true),
    TECLA_CONTROL: new PortugolVar("inteiro", 17, true),
    TECLA_D: new PortugolVar("inteiro", 68, true),
    TECLA_DECIMAL: new PortugolVar("inteiro", 110, true),
    TECLA_DELETAR: new PortugolVar("inteiro", 127, true),
    TECLA_DIVISAO: new PortugolVar("inteiro", 111, true),
    TECLA_E: new PortugolVar("inteiro", 69, true),
    TECLA_END: new PortugolVar("inteiro", 35, true),
    TECLA_ENTER: new PortugolVar("inteiro", 10, true),
    TECLA_ESC: new PortugolVar("inteiro", 27, true),
    TECLA_ESPACO: new PortugolVar("inteiro", 32, true),
    TECLA_F: new PortugolVar("inteiro", 70, true),
    TECLA_F1: new PortugolVar("inteiro", 112, true),
    TECLA_F10: new PortugolVar("inteiro", 121, true),
    TECLA_F11: new PortugolVar("inteiro", 122, true),
    TECLA_F12: new PortugolVar("inteiro", 123, true),
    TECLA_F13: new PortugolVar("inteiro", 61440, true),
    TECLA_F14: new PortugolVar("inteiro", 61441, true),
    TECLA_F15: new PortugolVar("inteiro", 61442, true),
    TECLA_F16: new PortugolVar("inteiro", 61443, true),
    TECLA_F17: new PortugolVar("inteiro", 61444, true),
    TECLA_F18: new PortugolVar("inteiro", 61445, true),
    TECLA_F19: new PortugolVar("inteiro", 61446, true),
    TECLA_F2: new PortugolVar("inteiro", 113, true),
    TECLA_F20: new PortugolVar("inteiro", 61447, true),
    TECLA_F21: new PortugolVar("inteiro", 61448, true),
    TECLA_F22: new PortugolVar("inteiro", 61449, true),
    TECLA_F23: new PortugolVar("inteiro", 61450, true),
    TECLA_F24: new PortugolVar("inteiro", 61451, true),
    TECLA_F3: new PortugolVar("inteiro", 114, true),
    TECLA_F4: new PortugolVar("inteiro", 115, true),
    TECLA_F5: new PortugolVar("inteiro", 116, true),
    TECLA_F6: new PortugolVar("inteiro", 117, true),
    TECLA_F7: new PortugolVar("inteiro", 118, true),
    TECLA_F8: new PortugolVar("inteiro", 119, true),
    TECLA_F9: new PortugolVar("inteiro", 120, true),
    TECLA_FECHA_COLCHETES: new PortugolVar("inteiro", 93, true),
    TECLA_G: new PortugolVar("inteiro", 71, true),
    TECLA_H: new PortugolVar("inteiro", 72, true),
    TECLA_HOME: new PortugolVar("inteiro", 36, true),
    TECLA_I: new PortugolVar("inteiro", 73, true),
    TECLA_IGUAL: new PortugolVar("inteiro", 61, true),
    TECLA_INSERT: new PortugolVar("inteiro", 155, true),
    TECLA_J: new PortugolVar("inteiro", 74, true),
    TECLA_K: new PortugolVar("inteiro", 75, true),
    TECLA_L: new PortugolVar("inteiro", 76, true),
    TECLA_LIMPAR: new PortugolVar("inteiro", 12, true),
    TECLA_M: new PortugolVar("inteiro", 77, true),
    TECLA_MENOS: new PortugolVar("inteiro", 45, true),
    TECLA_MENU_CONTEXTO: new PortugolVar("inteiro", 158, true),
    TECLA_MULTIPLICACAO: new PortugolVar("inteiro", 106, true),
    TECLA_N: new PortugolVar("inteiro", 78, true),
    TECLA_NUM_LOCK: new PortugolVar("inteiro", 144, true),
    TECLA_NUM_SEPARADOR_DECIMAL: new PortugolVar("inteiro", 108, true),
    TECLA_O: new PortugolVar("inteiro", 79, true),
    TECLA_P: new PortugolVar("inteiro", 80, true),
    TECLA_PAGE_DOWN: new PortugolVar("inteiro", 34, true),
    TECLA_PAGE_UP: new PortugolVar("inteiro", 33, true),
    TECLA_PAUSE: new PortugolVar("inteiro", 19, true),
    TECLA_PONTO_FINAL: new PortugolVar("inteiro", 46, true),
    TECLA_PONTO_VIRGULA: new PortugolVar("inteiro", 59, true),
    TECLA_PRINTSCREEN: new PortugolVar("inteiro", 154, true),
    TECLA_Q: new PortugolVar("inteiro", 81, true),
    TECLA_R: new PortugolVar("inteiro", 82, true),
    TECLA_S: new PortugolVar("inteiro", 83, true),
    TECLA_SCROLL_LOCK: new PortugolVar("inteiro", 145, true),
    TECLA_SETA_ABAIXO: new PortugolVar("inteiro", 40, true),
    TECLA_SETA_ACIMA: new PortugolVar("inteiro", 38, true),
    TECLA_SETA_DIREITA: new PortugolVar("inteiro", 39, true),
    TECLA_SETA_ESQUERDA: new PortugolVar("inteiro", 37, true),
    TECLA_SHIFT: new PortugolVar("inteiro", 16, true),
    TECLA_SUBTRACAO: new PortugolVar("inteiro", 109, true),
    TECLA_T: new PortugolVar("inteiro", 84, true),
    TECLA_TAB: new PortugolVar("inteiro", 9, true),
    TECLA_U: new PortugolVar("inteiro", 85, true),
    TECLA_V: new PortugolVar("inteiro", 86, true),
    TECLA_VIRGULA: new PortugolVar("inteiro", 44, true),
    TECLA_W: new PortugolVar("inteiro", 87, true),
    TECLA_WINDOWS: new PortugolVar("inteiro", 157, true),
    TECLA_X: new PortugolVar("inteiro", 88, true),
    TECLA_Y: new PortugolVar("inteiro", 89, true),
    TECLA_Z: new PortugolVar("inteiro", 90, true),

    tecla_pressionada(tecla) {
        self.runtime.expectType("tecla_pressionada", "tecla", tecla, "inteiro");
        return self.runtime.postMessageAndWaitForResponse({
        type: "keyboard.isKeyPressed",
        data: tecla.getValue()
        }).then(x => new PortugolVar("logico", x, true));
    },
    ler_tecla() {
        return self.runtime.postMessageAndWaitForResponse({
        type: "keyboard.waitForKey",
        data: tecla.getValue()
        }).then(x => new PortugolVar("inteiro", x, true));
    },
    alguma_tecla_pressionada() {
        return self.runtime.postMessageAndWaitForResponse({
        type: "keyboard.anyKeyPressed"
        }).then(x => new PortugolVar("logico", x, true));
    },
    caracter_tecla(tecla) {
        self.runtime.expectType("caracter_tecla", "tecla", tecla, "inteiro");
        return new PortugolVar("cadeia", String.fromCodePoint(tecla.getValue()), true)
    }
}`;
