name: Build and Deploy (Beta)
permissions:
  contents: read
on:
  push:
    branches:
      - beta
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup Node.js 📦
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Install dependencies 🔧
        run: npm ci --include=dev

      - name: Build code 🚚
        run: npm run build

      - name: Release front-end 🎢
        run: |
          sed -i -e 's/%COMMIT_SHA%/'"${GITHUB_SHA}"'/g' -e 's/%BUILD_DATE%/'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'/g' packages/ide/src/app/version.ts
          ./packages/ide/cleanup-icons.sh
          npm run release

      - name: Setup Firebase Hosting 🔥
        env:
          BETA_FIREBASE_PROJECT_ID: ${{ vars.BETA_FIREBASE_PROJECT_ID }}
          BETA_FIREBASE_HOSTING_SITE: ${{ vars.BETA_FIREBASE_HOSTING_SITE }}
        run: |
          jq -n --arg default "$BETA_FIREBASE_PROJECT_ID" '{ "projects": { "default": $default } }' > .firebaserc
          cat <<EOF | tee firebase.json
          {
            "hosting": {
              "site": "$BETA_FIREBASE_HOSTING_SITE",
              "public": "packages/ide/dist/browser",
              "headers": [
                {
                  "source": "/**",
                  "headers": [
                    {
                      "key": "Cache-Control",
                      "value": "max-age=900, stale-while-revalidate=180"
                    }
                  ]
                }
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }
          EOF

      - name: Deploy 🚀
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.BETA_FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ vars.BETA_FIREBASE_PROJECT_ID }}
          channelId: live
